### ISSUE TITLE
[debug] Debugging with eclipse IDE and GDB SEGGER J-Link shows no source

### ISSUE THREAD

**Issue by AuSchell** [openthread/ot-nrf528xx#35]
Hello

I've tried out this repo and it works so far, except for debugging. When i try to debug with the same configuration as in the openthread repo, i only get the disassembly view, but no .c source file where the code starts. It shows the message "No source available for "main() at 0x5b4"" in the window where i normally see the C code.

I'm using Eclipse IDE for C/C++ Developers Version: 2018-12 (4.10.0) and SEGGER J-Link GDB Server V6.62b.

Also, could you give me a tipp where to start if i want to add my own code?

Thanks in advance.

**Comment by LuDuda** [comment]
Hello @AuSchell,

Please post your question on the official [Nordic's devzone](https://devzone.nordicsemi.com/).

In general, we don't officially support the Eclipse environment. Based on the fact that Eclipse knows that you are in the `main()` function (so it can read symbols correctly) I would guess there is a problem with paths. Could you check what is the path to `main.c` that Eclipse looks for (maybe it's a relative path instead of absolute)?

In general, GDB has a command to substitute paths e.g.: `set substitute-path <from> <to>`
